"""empty message

Revision ID: b70cd40e22b6
Revises: 
Create Date: 2017-12-03 10:59:50.885996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b70cd40e22b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('token', sa.String(length=120), nullable=True),
    sa.Column('expire', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email')
    )
    op.create_table('card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=True),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('expire_year', sa.Integer(), nullable=True),
    sa.Column('expire_month', sa.Integer(), nullable=True),
    sa.Column('direct_debit', sa.Boolean(), nullable=True),
    sa.Column('purchase_limit', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('available_limit', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('spent', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('payment_day', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=80), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token')
    )
    op.create_table('original_invoices_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dollar', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('previous_amount', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('total_credits', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('total_debits', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('payment_date', sa.DATE(), nullable=True),
    sa.Column('effective_monthly_rate', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('effective_yearly_rate', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('rotational_rate', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('rotational_cash_rate', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('fine_rate', sa.DECIMAL(precision=18, scale=2), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('amount'),
    sa.UniqueConstraint('dollar'),
    sa.UniqueConstraint('effective_monthly_rate'),
    sa.UniqueConstraint('effective_yearly_rate'),
    sa.UniqueConstraint('fine_rate'),
    sa.UniqueConstraint('payment_date'),
    sa.UniqueConstraint('previous_amount'),
    sa.UniqueConstraint('rotational_cash_rate'),
    sa.UniqueConstraint('rotational_rate'),
    sa.UniqueConstraint('total_credits'),
    sa.UniqueConstraint('total_debits')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('original_invoices_history')
    op.drop_table('integration')
    op.drop_table('card')
    op.drop_table('user')
    # ### end Alembic commands ###
